/**
 * 📜 Privacy Policy — Sprint 9 Task 3.
 *
 * Covers all features Sprints 1-8:
 * voice, camera/QR, marketplace, translation, TeachMe,
 * achievements, weekly summary, waitlist.
 *
 * Contact: hello@fablefur.com
 */
import { ScrollView, Text, StyleSheet, View } from "react-native";
import { colors, spacing, borderRadius, fontSize } from "../src/theme";

const SECTIONS = [
    {
        title: "Your Data, Your Hardware",
        body: "Fireside runs entirely on your home computer. Your conversations, memories, and files stay on your hardware. We never see them, never store them, and never train on them.",
    },
    {
        title: "Voice Mode",
        body: "Microphone audio is sent to your home PC for speech recognition (Whisper). Audio is never stored or sent to any cloud service. Voice processing happens locally on your GPU.",
    },
    {
        title: "Camera (QR Pairing)",
        body: "Camera is used only for scanning QR pairing codes to connect your phone to your home PC. No photos are taken or stored.",
    },
    {
        title: "Marketplace",
        body: "Marketplace browsing sends requests to your home PC's plugin registry. No browsing data is shared externally. Purchases are processed through your home PC's marketplace plugin.",
    },
    {
        title: "Translation",
        body: "Text translation is performed by NLLB-200 running on your home PC. Translated text never leaves your local network.",
    },
    {
        title: "TeachMe",
        body: "Facts you teach your companion are stored on your home PC in its memory files. This data remains on your hardware and is never uploaded.",
    },
    {
        title: "Achievements & Progress",
        body: "Achievement progress, XP, levels, and streaks are stored on your home PC. Your companion's growth data never leaves your network.",
    },
    {
        title: "Weekly Summary",
        body: "Weekly activity statistics are generated from data on your home PC. Summaries are computed locally and displayed on your phone.",
    },
    {
        title: "Hosted Waitlist",
        body: "If you join the hosted waitlist, your email address is stored on our servers. No other data is collected until your hosted instance is provisioned. We will only use your email to notify you when your private AI is ready.",
    },
    {
        title: "Notifications",
        body: "Push notifications are sent through Apple's Push Notification Service (APNs). Notification content is generated by your home PC and routed through standard platform channels. We do not read notification content.",
    },
    {
        title: "Analytics",
        body: "Fireside does not collect analytics, usage data, or telemetry. We don't know how you use the app, how often you open it, or what you say to your companion.",
    },
    {
        title: "Data Deletion",
        body: "To delete all your data, simply stop running Fireside on your home PC. All companion data, memories, and files are stored locally and are removed when you uninstall. For waitlist users, email hello@fablefur.com to request removal.",
    },
];

export default function PrivacyPolicy() {
    return (
        <ScrollView style={styles.container} contentContainerStyle={styles.content}>
            <Text style={styles.title}>🔒 Privacy Policy</Text>
            <Text style={styles.subtitle}>Last updated: March 2026</Text>

            <View style={styles.heroCard}>
                <Text style={styles.heroText}>
                    Your AI, your hardware, your data. Zero cloud. Zero tracking. Zero compromise.
                </Text>
            </View>

            {SECTIONS.map((section, idx) => (
                <View key={idx} style={styles.section}>
                    <Text style={styles.sectionTitle}>{section.title}</Text>
                    <Text style={styles.sectionBody}>{section.body}</Text>
                </View>
            ))}

            <View style={styles.contactSection}>
                <Text style={styles.contactTitle}>Questions?</Text>
                <Text style={styles.contactText}>hello@fablefur.com</Text>
            </View>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bgPrimary },
    content: { paddingHorizontal: spacing.lg, paddingTop: 60, paddingBottom: spacing.xxxl + 40 },
    title: { fontFamily: "Inter_700Bold", fontSize: fontSize.xxl, color: colors.textPrimary, marginBottom: spacing.xs },
    subtitle: { fontFamily: "Inter_400Regular", fontSize: fontSize.xs, color: colors.textDim, marginBottom: spacing.xl },
    heroCard: { backgroundColor: colors.neonGlow, borderRadius: borderRadius.lg, borderWidth: 1, borderColor: colors.neonBorder, padding: spacing.xl, marginBottom: spacing.xl },
    heroText: { fontFamily: "Inter_600SemiBold", fontSize: fontSize.md, color: colors.neon, textAlign: "center", lineHeight: 22 },
    section: { marginBottom: spacing.lg },
    sectionTitle: { fontFamily: "Inter_600SemiBold", fontSize: fontSize.md, color: colors.textPrimary, marginBottom: spacing.xs },
    sectionBody: { fontFamily: "Inter_400Regular", fontSize: fontSize.xs, color: colors.textSecondary, lineHeight: 20 },
    contactSection: { alignItems: "center", marginTop: spacing.xl, paddingTop: spacing.xl, borderTopWidth: 1, borderTopColor: colors.glassBorder },
    contactTitle: { fontFamily: "Inter_600SemiBold", fontSize: fontSize.sm, color: colors.textDim, marginBottom: spacing.xs },
    contactText: { fontFamily: "Inter_400Regular", fontSize: fontSize.md, color: colors.neon },
});
