#!/usr/bin/env python3
"""
valhalla_cli.py — CLI for the Valhalla Mesh.

Usage:
    valhalla init                     Generate valhalla.yaml interactively
    valhalla start                    Start Bifrost server
    valhalla status                   Show node status
    valhalla plugin install <name>    Install a plugin
    valhalla plugin list              List installed plugins
    valhalla join <host>              Join a mesh (host format: name@ip or ip:port)
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.request
from pathlib import Path


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _api(method: str, path: str, host: str = "127.0.0.1:8765",
         data: dict = None) -> dict:
    """Call a Bifrost API endpoint."""
    url = f"http://{host}{path}"
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": "application/json"} if body else {},
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode() if e.fp else ""
        try:
            return {"error": json.loads(body_text).get("detail", body_text)}
        except Exception:
            return {"error": body_text or str(e)}
    except urllib.error.URLError:
        return {"error": f"Cannot connect to Bifrost at {host}. Is it running?"}


def _print_kv(data: dict, indent: int = 0) -> None:
    """Pretty-print a dict as key: value."""
    prefix = "  " * indent
    for k, v in data.items():
        if isinstance(v, dict):
            print(f"{prefix}{k}:")
            _print_kv(v, indent + 1)
        elif isinstance(v, list):
            print(f"{prefix}{k}: {', '.join(str(x) for x in v)}")
        else:
            print(f"{prefix}{k}: {v}")


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_init(args):
    """Interactive valhalla.yaml generator."""
    output = Path(args.output) if args.output else Path("valhalla.yaml")

    if output.exists() and not args.force:
        print(f"⚠  {output} already exists. Use --force to overwrite.")
        return 1

    print("⚡ Valhalla Mesh — Node Setup\n")

    name = input("Node name [odin]: ").strip() or "odin"
    role = input("Role (orchestrator/backend/memory/security/worker) [orchestrator]: ").strip() or "orchestrator"
    port = input("Port [8765]: ").strip() or "8765"

    model = input("Default model [llama/Qwen3.5-35B-A3B-8bit]: ").strip() or "llama/Qwen3.5-35B-A3B-8bit"

    yaml_content = f"""# ─────────────────────────────────────────────────────────────
# Valhalla Mesh V2 — Node Config
# Generated by 'valhalla init'
# ─────────────────────────────────────────────────────────────

node:
  name: {name}
  role: {role}
  port: {port}

mesh:
  auth_token: "change-me-to-a-long-random-string"
  nodes: {{}}

dashboard:
  auth_key: "change-me-dashboard-key"
  allow_localhost: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"

models:
  default: {model}
  providers:
    llama:
      url: http://127.0.0.1:8080/v1
      key: local
      api: openai-completions
  aliases:
    local: {model}

plugins:
  enabled:
    - model-switch
    - watchdog

soul:
  identity: mesh/souls/IDENTITY.{name}.md
  personality: mesh/souls/SOUL.{name}.md
  user_profile: mesh/souls/USER.{name}.md
"""

    output.write_text(yaml_content, encoding="utf-8")
    print(f"\n✅ Written to {output}")
    print(f"   Next: python3 bifrost.py")

    # Create soul file stubs
    soul_dir = Path("mesh/souls")
    soul_dir.mkdir(parents=True, exist_ok=True)
    for prefix, template in [
        ("IDENTITY", f"# IDENTITY.md - {name.title()}\n\n- **Name:** {name.title()}\n- **Role:** {role}\n"),
        ("SOUL", f"# SOUL.md -- {name.title()}\n\n_Your personality goes here._\n"),
        ("USER", f"# USER.md - About Your Human\n\n- **Human:** [Your name]\n"),
    ]:
        path = soul_dir / f"{prefix}.{name}.md"
        if not path.exists():
            path.write_text(template, encoding="utf-8")
            print(f"   Created {path}")

    return 0


def cmd_start(args):
    """Start Bifrost server."""
    bifrost = Path("bifrost.py")
    if not bifrost.exists():
        print("Error: bifrost.py not found. Run from the valhalla-mesh-v2 directory.")
        return 1

    port_arg = f"--port {args.port}" if args.port else ""
    cmd = f"python3 bifrost.py {port_arg}".strip()
    print(f"⚡ Starting Bifrost: {cmd}")
    os.execvp("python3", cmd.split())


def cmd_status(args):
    """Show node status."""
    host = args.host or "127.0.0.1:8765"
    data = _api("GET", "/api/v1/status", host)

    if "error" in data:
        print(f"❌ {data['error']}")
        return 1

    print(f"⚡ Valhalla Node: {data.get('node', 'unknown')}")
    print(f"   Role:    {data.get('role', 'unknown')}")
    print(f"   Model:   {data.get('model', 'unknown')}")
    print(f"   Uptime:  {data.get('uptime_human', 'unknown')}")
    print(f"   Plugins: {data.get('plugins_loaded', 0)}")
    print(f"   Status:  {data.get('status', 'unknown')}")

    gpu = data.get("gpu", {})
    if gpu and gpu.get("name"):
        print(f"   GPU:     {gpu['name']} ({gpu.get('vram_total_gb', '?')} GB)")

    return 0


def cmd_plugin_install(args):
    """Install a plugin."""
    host = args.host or "127.0.0.1:8765"
    data = _api("POST", "/api/v1/plugins/install", host, {"name": args.name})

    if "error" in data:
        print(f"❌ {data['error']}")
        return 1

    print(f"✅ {data.get('message', 'Plugin installed')}")
    return 0


def cmd_plugin_list(args):
    """List installed plugins."""
    host = args.host or "127.0.0.1:8765"
    data = _api("GET", "/api/v1/plugins", host)

    if "error" in data:
        print(f"❌ {data['error']}")
        return 1

    plugins = data.get("plugins", [])
    if not plugins:
        print("No plugins installed.")
        return 0

    print(f"⚡ Installed Plugins ({len(plugins)}):\n")
    for p in plugins:
        name = p.get("name", "?")
        version = p.get("version", "?")
        desc = p.get("description", "")
        print(f"  {name} v{version}")
        if desc:
            print(f"    {desc}")
    return 0


def cmd_join(args):
    """Join a mesh."""
    # Parse host: "name@ip:port" or "ip:port" or "ip"
    target = args.host
    if "@" in target:
        _, target = target.split("@", 1)
    if ":" not in target:
        target = f"{target}:8765"

    print(f"⚡ Joining mesh at {target}...")

    # 1. Get a join token
    token_data = _api("POST", "/api/v1/mesh/join-token", target)
    if "error" in token_data:
        print(f"❌ {token_data['error']}")
        return 1

    token = token_data.get("token", "")
    if not token:
        print("❌ Failed to get join token")
        return 1

    print(f"   Got join token (expires in {token_data.get('expires_in_seconds', '?')}s)")

    # 2. Load our config
    import socket
    node_name = "unknown"
    node_role = "worker"
    try:
        import yaml
        config = yaml.safe_load(Path("valhalla.yaml").read_text())
        node_name = config.get("node", {}).get("name", socket.gethostname().lower())
        node_role = config.get("node", {}).get("role", "worker")
    except Exception:
        node_name = socket.gethostname().lower().split(".")[0]

    # 3. Detect our IP
    my_ip = "127.0.0.1"
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        my_ip = s.getsockname()[0]
        s.close()
    except Exception:
        pass

    # 4. Announce
    announce_data = _api("POST", "/api/v1/mesh/announce", target, {
        "name": node_name,
        "ip": my_ip,
        "port": 8765,
        "role": node_role,
        "token": token,
    })

    if "error" in announce_data:
        print(f"❌ {announce_data['error']}")
        return 1

    final_name = announce_data.get("name", node_name)
    renamed = announce_data.get("renamed", False)

    print(f"✅ {announce_data.get('message', 'Joined mesh')}")
    if renamed:
        print(f"   (Renamed from {node_name} → {final_name})")

    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        prog="valhalla",
        description="Valhalla Mesh CLI",
    )
    parser.add_argument("--host", help="Bifrost host:port (default: 127.0.0.1:8765)")
    sub = parser.add_subparsers(dest="command")

    # init
    init_p = sub.add_parser("init", help="Generate valhalla.yaml interactively")
    init_p.add_argument("--output", "-o", help="Output file path")
    init_p.add_argument("--force", "-f", action="store_true", help="Overwrite existing")

    # start
    start_p = sub.add_parser("start", help="Start Bifrost server")
    start_p.add_argument("--port", "-p", help="Override port")

    # status
    sub.add_parser("status", help="Show node status")

    # plugin
    plugin_p = sub.add_parser("plugin", help="Plugin management")
    plugin_sub = plugin_p.add_subparsers(dest="plugin_command")
    install_p = plugin_sub.add_parser("install", help="Install a plugin")
    install_p.add_argument("name", help="Plugin name")
    plugin_sub.add_parser("list", help="List installed plugins")

    # join
    join_p = sub.add_parser("join", help="Join a mesh")
    join_p.add_argument("host", help="Mesh host (e.g. odin@192.168.1.10:8765)")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    handlers = {
        "init": cmd_init,
        "start": cmd_start,
        "status": cmd_status,
        "join": cmd_join,
    }

    if args.command == "plugin":
        if args.plugin_command == "install":
            return cmd_plugin_install(args)
        elif args.plugin_command == "list":
            return cmd_plugin_list(args)
        else:
            plugin_p.print_help()
            return 1

    handler = handlers.get(args.command)
    if handler:
        return handler(args)
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main() or 0)
